### PR TITLE
Display repos description in the feed item descriptions

### PR DESCRIPTION
**Pull request by Florent2**
Hi Oscar!

Here is a commit to have the repos description displayed directly in the feed. I think that's quite helpful. Unfortunately the repos descriptions are not displayed in the language specific views, so the repos descriptions are displayed only in the 'All Languages' feeds.

I've left a feature request in the GitHub support interface to have the repos descriptions in the language specific views. If GitHub adds it one day, I would send you another patch.

A workaround would be to fetch a repos description through the GitHub repositories API (http://develop.github.com/p/repo.html) but that would complexify a bit the github-trends code.

### CODE REVIEW

**Comment by oscardelben** [comment]
Thank you, I've added you as a contributor as well in the Readme. I pushed online, let me know if it works as you'd expect.

**Comment by Florent2** [comment]
Thanks Oscar! I've checked online, when for now the description does not show up: feed://github-trends.oscardelben.com/explore/today.xml

**Comment by oscardelben** [comment]
Hi, is it working for you now? I have no idea what's wrong.

**Comment by Florent2** [comment]
No, it's not working. Is it working for you? When I run the code locally, it's working.

**Comment by oscardelben** [comment]
Sorry, it should be working now.

**Comment by Florent2** [comment]
Hi Oscar, that's not working for me. For the languages feeds it's working, but for the 'All Languages' it does not work.

I've cloned your repository (with the last commit cc70542cef1964e85f10), and it's working when I try locally.

**Comment by oscardelben** [comment]
I wasn't expiring the cache! Fixed that, thanks a lot.

**Comment by Florent2** [comment]
Indeed, it's working now :) Thanks!

**Pull request merged**
